---
title: "R语言编程篇——异常处理"
date: 2019-07-23
categories:
  - R语言
  - 编程
tags:
  - R语言编程
keywords:
  - R语言
  - 面向函数的编程
thumbnailImagePosition: left
thumbnailImage: https://i.postimg.cc/SK6LcHn4/image.png
distribute: https://i.postimg.cc/KYSrkmvQ/image.png
---

程序在执行的过程中，遇到错误输入，或者命令执行不当，往往需要抛出**异常**。因此处理异常、程序调试也是编程必不可少的一部分。这篇文集将总结R语言中的**异常处理**。

<!--more-->

<!-- toc -->


## 1、生成异常

R语言中的异常也可以被称为**状态**（**condition**），状态可以由两部分组成：**异常信息、异常命令**（**message、call**），可以分别表示 *为什么触发异常* 以及 *触发异常的命令* 。我们可以分别使用{{< hl-text primary >}}conditionCall、conditionMessage{{< /hl-text >}}函数，取出状态的这两个部分。

默认情况下状态可以分为三种不同的类型：**错误、警告、提示**（**error、warning、message**），这三种类型的状态都是以S3对象的方式（class属性）继承了**condition**。我们可以分别使用{{< hl-text primary >}}simpleCondition、simpleError、simpleWarning、simpleMessage{{< /hl-text >}}函数，生成相应类型的状态。

我们可以生成自定义类型的状态，最简单的方法就是修改class属性。之前我们就介绍过，class属性会影响到S3对象的继承关系以及S3函数的分发，之后的文章中我们将更加详细的总结这一点。总之，这里的class属性决定了状态的继承关系以及捕获状态的方式，所以修改时需要特别小心。保险起见我们也可以使用便捷函数，比如通过{{< hl-text primary >}}errorCondition(message, call, class){{< /hl-text >}}的形式，生成一个自定义的错误状态。类似的，我们也可以使用{{< hl-text primary >}}warningCondition{{< /hl-text >}}函数，生成自定义的警告状态。

```R
# 状态可以由异常信息和异常命令组成
> simpleCondition(message = "异常信息", call = quote(f(x)))
<simpleCondition in f(x): 异常信息>

# 自定义错误状态
> cond <- errorCondition("错误状态", class = "my_error"); cond
<my_error: 错误状态>
> class(cond)
[1] "my_error"  "error"     "condition"
```

<br>

## 2、抛出异常

一般情况下，三种类型的状态分别对应三种不同的抛出异常方式，即R语言中的三个函数{{< hl-text primary >}}stop、warning、message{{< /hl-text >}}。其中**stop**函数默认抛出错误状态，表示代码执行到这里遇到了不可继续执行的命令，所以抛出异常并终止执行。**warning**函数默认抛出警告状态，表示代码执行到这里虽然遇到了错误，但是可以继续执行。而**message**函数默认抛出提示状态，表示代码执行到这里可能会产生错误或者使人迷惑的结果，需要提示使用者相应的信息。

除了抛出状态，以上三个函数还可以直接将字符串转化为相应的状态抛出，此时如果在函数体内部或者函数调用命令中使用**stop、warning**，还可以使用**call.**参数决定是否将调用函数的命令作为状态的异常命令；对于**message**函数，我们还可以使用**appendLF**参数，决定是否将提示信息作为单独的一行。需要特别注意的是，**warning**函数默认会在命令结束时才打印警告信息，当然我们也可以通过**immediate.**参数修改这一设定。

```R
# 使用stop函数终止程序
> f <- function() {
+   stop("命令执行失败！"); 
+   print(1)
+ }; f()
Error in f() : 命令执行失败！

# 使用warning函数不会终止程序
> f <- function() {
+   warning("命令执行出错！", immediate. = TRUE); 
+   print(1)
+ }; f()
Warning in f() : 命令执行出错！
[1] 1

# 使用message函数
> cat(message("提示信息：", appendLF = F), "def")
提示信息： def
```

当然，除了以上三个函数，R语言中还有其它的快捷函数也可以抛出异常。比如我们在上一篇文章中介绍到的**stopifnot**函数，以及专用于打印程序包载入信息的{{< hl-text primary >}}packageStartupMessage{{< /hl-text >}}函数等。

<br>

## 2、处理异常

处理异常最简单的方法就是忽略异常，但这种方法不能从根本上解决异常，所以无法压抑**stop**函数抛出的异常。压抑不同函数抛出的异常需要用到**supress**家族中不同的函数。比如：对于**warning**函数抛出的异常，我们可以使用{{< hl-text primary >}}suppressWarnings{{< /hl-text >}}函数压抑，对于**message**函数抛出的异常，可以使用{{< hl-text primary >}}suppressMessages{{< /hl-text >}}函数压抑。

我们也可以使用{{< hl-text primary >}}tryCatch(expr, ..., finally){{< /hl-text >}}或者{{< hl-text primary >}}withCallingHandlers(expr, ...){{< /hl-text >}}的形式处理异常，其中的不定长参数可以是任意多个`conditionClass = handler`形式的**异常处理子句**（**restart**），表示一旦执行**expr**时遇到某种**condition**，就执行**handle**。注意处理父类异常的子句也可以用于处理子类异常，而这里的异常处理顺序是按照子句的先后顺序进行的，所以处理多个异常时，我们最好按照异常的继承关系，先处理子类异常，再处理父类异常。

**tryCatch、withCallingHandlers**的区别主要在于：首先，**tryCatch**多了一个**finally**子句，表示无论是否遇到异常，在命令结束时都需要执行的内容，特别适用于关闭文件资源链接等情况。此外，**withCallingHandlers**处理了**warning、message**等函数抛出的异常后，还会继续执行**expr**，而**tryCatch**一旦处理了异常就不会再继续执行**expr**。最后，**withCallingHandlers**即使处理了异常，依然会打印异常信息，而**tryCatch**直接将异常传递给了异常处理子句，如果不在异常处理子句中显示的打印异常，异常就不会被打印。

```R
# 处理父类异常的异常处理子句也可以用于处理子类异常
> cond  <- errorCondition(class = "my_error", message = "错误状态")
> tryCatch(stop(cond), 
+          error =  function(cond) print("处理父类错误状态..."),
+          finally = print("错误处理完毕！"))
[1] "处理父类错误状态..."
[1] "错误处理完毕！"
```

此外R语言中的{{< hl-text primary >}}try{{< /hl-text >}}函数也可以用于异常处理，它实际上调用了**tryCatch**函数，可以把错误信息重定向到文件、或者**try-error**类型的对象中。

<br>

## 4、函数调试

当调用函数遇到异常时，我们可能需要知道异常具体产生在什么位置（**定位异常**）。此时我们可以使用{{< hl-text primary >}}geterrmessage、warnings{{< /hl-text >}}函数，查看异常缓存区中的错误、警告信息。也可以使用{{< hl-text primary >}}traceback{{< /hl-text >}}函数，列出错误产生时所有压栈函数的调用命令。当然，我们还可以使用{{< hl-text primary >}}debug{{< /hl-text >}}家族的函数手动进行调试，这种方法结合**Rstudio**等R语言IDE工具会更加高效。

对函数使用**debug**，相当于开启了函数的调试标识，此时我们再使用函数时就会进入**函数调试模式**。在函数调试模式中，我们可以输入**n**逐步执行命令（嵌套调用的命令在这里被认为是一步，相当于**step over**），输入**s**进入函数内部进行调试（相当于**step into**），输入**f**持续执行直到当前函数或循环执行完毕（相当于**step out**），输入**c**持续执行直到遇到断点，输入**Q**退出调试模式，输入**where**查看所有压栈函数被调用时的命令（相当于**sys.calls**），输入**help**查看以上使用帮助。或者我们也可以输入R语言代码，查看它们在函数内部执行的效果。

在函数体内部调用{{< hl-text primary >}}browser{{< /hl-text >}}，相当于在函数中打上了断点。我们可以使用**expr**参数标记是否启用断点，一旦启用断点无论函数的调试标识是否打开，只要执行到**browser**语句处就会强制进入调试模式。

我们还可以使用{{< hl-text primary >}}trace{{< /hl-text >}}家族的函数，追踪调试一个函数。**trace**函数中的**at、tracer**参数结合使用，表示当函数执行到第几步时，执行相应的命令；同理我们也可以使用**exit**参数，设定函数退出时需要执行的命令。

最后，我们还可以使用{{< hl-text primary >}}recover{{< /hl-text >}}函数（`options(error = recover)`），我们可以选择错误产生时任一压栈函数的调用命令进行调试。

<br>

{{< image group="group:异常处理" classes="fancybox nocaption fig-50" src="https://i.postimg.cc/L5pzCpbv/debug.png" title="debug" >}}

{{< image group="group:异常处理" classes="fancybox nocaption fig-50" src="https://i.postimg.cc/vTt5CKRy/recover.png" title="recover" >}}

{{< image group="group:异常处理" classes="fancybox nocaption fig-33" src="https://i.postimg.cc/7673n6mf/browser.png" title="browser" >}}

{{< image group="group:异常处理" classes="fancybox nocaption fig-66 clear" src="https://i.postimg.cc/T2VjyKKs/trace.png" title="trace" >}}

<br>

{{< note "思考思考" "#e6e6ff" >}}
- **message**函数与**packageStartupMessage**函数的差异何在？
- 如何用**tryCatch**函数实现**suppressWarnings**函数？
- 由**recover**函数开启的调试模式会增加新的压栈函数，这是设计败笔吗？

{{< /note >}}

<br>
